### ISSUE TITLE
Whitespace arround tags

### ISSUE THREAD

**Issue by vdboor** [speedmax/h2o-php#16]
When template tags are indented with the HTML code, the HTML tags get double indention. I find this output ugly, and would like to see it differently.

I think the following would lead to much to both clean template code and clean output.
- when the full line has a template tag, pretend the full line doesn't exist.
- if there is other code at the line, preserve whitespace; pretend the template tag didn't exist.

I hope you agree :)

**Comment by speedmax** [comment]
H2o supports a striping tag format

For example
if you want to strip whitespace on the left, u can do this

{%- tag_name %}

It works for right hand side too.

Cheers

**Comment by vdboor** [comment]
Sounds like a solution to me :)

With the latest git checkout, I do get an exception:

Uncaught exception 'H2o_Error' with message '- tag doesn't exist'

I'm using a {%- for .. in %} loop.
