### ISSUE TITLE
relative_time doesn't work when the timestamp given is in the future. 

### ISSUE THREAD

**Issue by hackerone** [speedmax/h2o-php#27]
relative_time doesn't work when the timestamp given is in the future. i've fixed it in my versions. since i don't have permissions to edit the source, i'm posting the change below.. 

```
static function relative_time($timestamp, $format = 'g:iA') {
```

...
        if($delta < 0){
            $delta = abs($delta);
            $future = 1;
        }
...
        if($future)return "in $string";
               else return "$string ago";
    }

**Comment by buchin** [comment]
It seems speedmax is offline at the moment, would you paste your crrent changed version in gist? https://gist.github.com/

I'll try to include that in my forked version of h2o and request a pull from speedmax

**Comment by hackerone** [comment]
https://gist.github.com/729132
