### ISSUE TITLE
methods not called for objects?

### ISSUE THREAD

**Issue by christaggart** [speedmax/h2o-php#33]
I have an object with child objects that have their own methods. According to the documentation, these should be callable via the dot notation, should they not?

Example:
 {% for index, object in c.objects %}
        <li>{{ object.name}} | {{ object.method_name }} </li>
{% endfor %}

object.method_name returns a string, but it's not appearing in the rendered page?

**Comment by christaggart** [comment]
Didn't realize I had to add:
   var $h2o_safe = array('method_name');
inside the class to make the methods accessible. Should flag that in the documentation somewhere.

**Comment by cyberklin** [comment]
in my projects i disable method protecting (see my https://github.com/cyberklin/h2o-php/commit/737ed4effca92fc57c2f71183bd26217e872690e for making it configurable)

**Comment by christaggart** [comment]
great idea. thanks!
