### ISSUE TITLE
PHP Notice in h20/loaders.php file

### ISSUE THREAD

**Issue by brunobraga** [speedmax/h2o-php#44]
The class H2o_File_Loader that extends H2o_Loader tries to use a private property from H2o_Loader, giving the alarm:

Notice: Undefined property: H2o_File_Loader::$cache in /var/www/h2o/h2o/loaders.php on line 50

To solve the problem, just change the line 11 of loaders.php:

```
private $cache = false;
```

to:

```
protected $cache = false;
```

This is so small issue the I figured it wasn't worth to fork your code.

Very nicely done! I was looking for something Django alike to deal with templating... the alternatives, sad to say, suck!

Cheers,

**Comment by brunobraga** [comment]
Probably an old version... corrected since 2009 commit... sorry.

**Comment by speedmax** [comment]
Thx @brunobraga for helping out
