### ISSUE TITLE
Filters in if Tags?

### ISSUE THREAD

**Issue by DarkAxi0m** [speedmax/h2o-php#69]
Is it possible to use a Filter within an if tag? e.g.

```
{% if people | length <= 1 %}      
    There is only one person
{% else %}                      
   There is more than one person
{% endif %} 
```

**Comment by speedmax** [comment]
Array like object supports these method calls.. (length, first, last ..etc).. see Context#resove_variable method in context.php for detail

{% if people.length <= 1 %}

**Comment by DarkAxi0m** [comment]
Thankyou
